name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Add and commit changes
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "djusa1221@gmail.com"
        git config --global user.name "Arnie Ungvary"
        git add .
        git commit -m "Automated commit by GitHub Actions"
        git push https://gh-token:$GH_TOKEN@github.com/ImArnie/MovieNode.git
